import os
from dotenv import load_dotenv
import google.generativeai as genai

load_dotenv()

api_key = os.getenv("GEMINI_API_KEY")

if api_key:
    genai.configure(api_key=api_key)
    model = genai.GenerativeModel("gemini-2.5-flash")
else:
    model = None


def explain_threat(
    destination_port,
    flow_duration,
    prediction,
    risk,
    tactic,
    technique,
    technique_id,
    description,
    mitigation
):
    """
    Generates an AI explanation for a detected cyber threat
    using Google Gemini.
    """

    if model is None:
        return "❌ Gemini API Key not found. Please check your .env file."

    prompt = f"""
You are an expert Security Operations Center (SOC) Analyst.

Analyze the following suspicious network traffic.

======================================================
NETWORK INFORMATION
======================================================

Destination Port : {destination_port}
Flow Duration    : {flow_duration}

Attack Type      : {prediction}

Risk Level       : {risk}

======================================================
MITRE ATT&CK MAPPING
======================================================

Tactic           : {tactic}

Technique        : {technique}

Technique ID     : {technique_id}

Description:

{description}

Recommended Mitigation:

{mitigation}

======================================================

Provide the response in the following format:

### Threat Summary
Briefly summarize the detected threat.

### Why is this attack dangerous?
Explain the security risks.

### MITRE ATT&CK Explanation
Explain the mapped tactic and technique.

### Indicators of Compromise (IoCs)
Mention possible IoCs related to this attack.

### Recommended Actions
Suggest what a SOC analyst should do immediately.

### Business Impact
Explain the possible impact on an organization.

Keep the response concise (under 200 words).
"""

    try:
        response = model.generate_content(prompt)

        if response and hasattr(response, "text"):
            return response.text.strip()

        return "No response generated by Gemini."

    except Exception as e:
        return f"Gemini Error: {str(e)}"